version: "3.8"
services:
  back-end:
      build:
        context: ./back-end
        dockerfile: Dockerfile
      ports:
        - 8081:8081
  front-end:
      build:
        context: ./front-end
        dockerfile: Dockerfile
      ports:
        - 8082:8082
#  nginx:
#      build:
#        context: ./nginx
#        dockerfile: Dockerfile
#      ports:
#        - 80:80